cherry-pick tagged bugfixes from `development` to `stabilization/25100` (01) (#19246)
* Fixes blendshapes ("morph targets") not working (#19151)

Fixes https://github.com/o3de/o3de/issues/19058

It turns out that the blend shape data was getting
the number of vertices from the mesh by dividing
the position buffer by 3 (3 floats per vertex),
but the position buffer was being aligned to some larger
multiple of 16 bytes.

Instead, I get the number of vertices by using the
m_numVertices value.

Signed-off-by: Nicholas Lawson <70027408+nick-l-o3de@users.noreply.github.com>

* Fixes in Python script to properly support custom splash screens and icons in Android builds. (#19161)

Signed-off-by: VladimirLagutin <vlagutin@tech-round.com>

* Fix Clang20 compile errors (#19163)

Signed-off-by: Markus Prettner <markus.prettner@huawei.com>

* Re-enable deprecated-this-capture warning (#19165)

Signed-off-by: Markus Prettner <markus.prettner@outlook.com>

* Add missing AZ_MONOLITHIC checks for using static vs shared AZ_BUDGET macros for Atom RHI (#19169)

Signed-off-by: Steve Pham <82231385+spham-amzn@users.noreply.github.com>

* Remove Clang -fno-relaxed-template-template-args compile option (#19177)

Signed-off-by: Markus Prettner <markus.prettner@outlook.com>

* Fix assert in CViewManager constructor due to improper usage of Aabb::SetMin/SetMax (#19189)

Signed-off-by: Markus Prettner <markus.prettner@outlook.com>

* Clang19 and higher Linux build issue fix. (#19197)

Signed-off-by: Joerg H. Mueller <joerg.mueller@huawei.com>

* Fixes release only clang compiler error due to unused variable in xcb: (#19200)

```
XcbNativeWindow.cpp:545:34: error: variable 'error' set but not used [-Werror,-Wunused-but-set-variable]
  545 |         if (xcb_generic_error_t* error = xcb_request_check(m_xcbConnection, cookie))
      |                                  ^
```

This is due to the AZ_Error macro being a no-op in release monolithic builds.

Signed-off-by: Nicholas Lawson <70027408+nick-l-o3de@users.noreply.github.com>

* Update CTEST_OPTIONS to exclude o3de_export_project (#19243)

Signed-off-by: Mike Chang <changml@amazon.com>

---------

Signed-off-by: Nicholas Lawson <70027408+nick-l-o3de@users.noreply.github.com>
Signed-off-by: VladimirLagutin <vlagutin@tech-round.com>
Signed-off-by: Markus Prettner <markus.prettner@huawei.com>
Signed-off-by: Markus Prettner <markus.prettner@outlook.com>
Signed-off-by: Steve Pham <82231385+spham-amzn@users.noreply.github.com>
Signed-off-by: Joerg H. Mueller <joerg.mueller@huawei.com>
Signed-off-by: Mike Chang <changml@amazon.com>
Co-authored-by: VladimirLagutin <123157206+VladimirLagutin@users.noreply.github.com>
Co-authored-by: Markus Prettner <markus.prettner@huawei.com>
Co-authored-by: Markus Prettner <markus.prettner@outlook.com>
Co-authored-by: Steve Pham <82231385+spham-amzn@users.noreply.github.com>
Co-authored-by: jhmueller-huawei <101700150+jhmueller-huawei@users.noreply.github.com>
Co-authored-by: Mike Chang <changml@amazon.com>